name: TechTrends - Package with Docker & Push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  package_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS }}

        - name: Build and push
          uses: docker/build-push-action@v2.10.0
          with:
            context: project
            push: true
            tags: techtrends:latest
